substitutions:
  node_name: bedroom-friend
  friendly_name: Bedroom
  scd41_suffix: " 2"
  display_rotation: "180"
  display_lambda: |-
    ${display_lambda_pms5003}
    ${display_lambda_scd41}

packages:
  d1_mini: !include esp8266-d1-mini.yaml
  dht22: !include dht22.yaml
  scd41: !include scd41.yaml
  pms5003: !include pms5003.yaml
  i2c: !include esp8266-i2c.yaml
  uart: !include esp8266-uart.yaml
  ssd1306: !include ssd1306.yaml
  sensorfriend: !include sensorfriend.yaml
