substitutions:
  node_name: outdoor-friend
  friendly_name: Outdoor
  display_lambda: |-
    ${display_lambda_ccs811}
    ${display_lambda_dht22}

packages:
  d1_mini: !include esp8266-d1-mini.yaml
  dht22: !include dht22.yaml
  ccs811: !include ccs811.yaml
  i2c: !include esp8266-i2c.yaml
  uart: !include esp8266-uart.yaml
  ssd1306: !include ssd1306.yaml
  sensorfriend: !include sensorfriend.yaml
