substitutions:
  display_lambda: ""

font:
  - file: ${fonts_root}/cozette.bdf
    id: cozette

display:
  - platform: ssd1306_i2c
    model: SSD1306 128x64
    id: ssd1306_display
    address: 0x3C
    contrast: 50%
    lambda: |-
      ${display_lambda}
